baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = 'æ–‡è¯—çš„ä¸‡äº‹å±‹'
theme = 'hugo-theme-stack'

[Params]
favicon = '/favicon.png'

[Params.Sidebar]
compact = false
emoji = 'ğŸ•µï¸â€â™‚ï¸'
subtitle = 'ä¸–ç•Œå•Šï¼Œçœ‹åˆ°æˆ‘ã€‚'

[Params.Sidebar.Avatar]
enabled = true
local = true
src = 'img/avatar.png'


[Params.Footer]
since = 2020
customText = 'ä¸–ç•Œå•Šï¼Œçœ‹åˆ°æˆ‘'